# Generated by Django 6.0.4 on 2026-05-17 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('emoji', models.CharField(default='💬', max_length=10)),
                ('atmosphere', models.CharField(choices=[('philosophy', 'Philosophy'), ('ai_research', 'AI Research'), ('deep_science', 'Deep Science'), ('psychology', 'Psychology'), ('entrepreneurship', 'Entrepreneurship')], default='philosophy', max_length=50)),
                ('accent_color', models.CharField(default='#7C6FF7', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spaces',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('post_type', models.CharField(choices=[('thought', 'Thought'), ('question', 'Question'), ('insight', 'Insight'), ('reference', 'Reference')], default='thought', max_length=20)),
                ('atmosphere', models.CharField(choices=[('calm', 'Calm'), ('heated', 'Heated'), ('beginner', 'Beginner Friendly'), ('deep_theory', 'Deep Theory'), ('exploratory', 'Exploratory')], default='calm', max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='users.user')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='spaces.space')),
            ],
            options={
                'db_table': 'discussions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_curator_pick', models.BooleanField(default=False)),
                ('is_highlighted_insight', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='spaces.comment')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spaces.discussion')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('appreciate', 'Appreciate'), ('insightful', 'Insightful'), ('curious', 'Curious')], max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='spaces.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'comment_reactions',
                'unique_together': {('comment', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='DiscussionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('appreciate', 'Appreciate'), ('insightful', 'Insightful'), ('curious', 'Curious')], max_length=20)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='spaces.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'discussion_reactions',
                'unique_together': {('discussion', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='SavedDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='spaces.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_discussions', to='users.user')),
            ],
            options={
                'db_table': 'saved_discussions',
                'unique_together': {('discussion', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('curator', 'Curator'), ('scholar', 'Scholar'), ('mentor', 'Mentor')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to='users.user')),
            ],
            options={
                'db_table': 'space_memberships',
                'unique_together': {('space', 'user')},
            },
        ),
    ]
