# Generated by Django 6.0.4 on 2026-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_add_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
