# Generated by Django 6.0.4 on 2026-05-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_space_slug'),
        ('spaces', '0003_space_description_and_scheduled_room'),
    ]

    operations = [
    ]
