# Generated by Django 6.0.4 on 2026-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_spacereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('superhost', 'SuperHost'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
